function x_dot = odefcn(t,in2,in3,in4)
%ODEFCN
%    X_DOT = ODEFCN(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Mar-2025 17:33:26

alpha_ang = in3(2,:);
g = in4(1,:);
length = in4(4,:);
m = in4(2,:);
radius = in4(3,:);
theta = in2(5,:);
theta_dot = in2(6,:);
thrust = in3(1,:);
v_1 = in2(3,:);
v_2 = in2(4,:);
t2 = cos(alpha_ang);
t3 = sin(alpha_ang);
t4 = cos(theta);
t5 = sin(theta);
t6 = 1.0./m;
x_dot = [v_1;v_2;t6.*(t2.*t5.*thrust+t3.*t4.*thrust);-t6.*(g.*m-t2.*t4.*thrust+t3.*t5.*thrust);theta_dot;(length.*t3.*thrust)./((length.^2.*m)./2.0+(m.*radius.^2)./3.0)];
end
